config/routes.rb
Rails.application.routes.draw do

  resources :pins

  get ':username' => 'users#show', as: 'user'
  devise_for :users

  root 'home#index'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  validates_presence_of :description, :pin_image

  belongs_to :user

  has_attached_file :pin_image, styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :pin_image, content_type: /\Aimage\/.*\Z/


def repost
end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


has_many :pins, dependent: :destroy
validates_uniqueness_of :username

has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates_presence_of :username

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :setup_devise_params, if: :devise_controller?

  def after_sign_in_path_for(model)
    pins_path
  end

  def after_sign_up_path_for(model)
    pins_path
  end

protected
def setup_devise_params
  devise_parameter_sanitizer.for(:sign_up) << [:username, :avatar]
  devise_parameter_sanitizer.for(:account_update) << [:username, :bio, :avatar]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, except: [:index, :show]
before_action :correct_user, only: [:edit, :update, :destroy]

# GET /images



  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    p pin_params
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to pins_path, notice: 'Pin was successfully created.' }
        format.json { render  :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render  :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:title, :description, :pin_image)
    end

    def correct_user
    @pin = current_user.pins.find_by(id: params[:id])
    redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
  @user = User.find_by username: params[:username]
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="picheader">
  <h1>Find and enjoy the view</h1>
</div>

<div class="pink">
  <div class ="red">
    <div class ="insidered">
        <div class = "content">
          <h3>Find your next lookout.</h3>
          <p>Welcome to The View. Your online portal to find the exact spot of breathe taking views in your area and around the world. </p>
    </div>
</div>
</div>
</div>

<div class ="white">
  <h2>Search. Share. Then Experience</h2>
  <div class ="boxes">
    <div class= "box1">
      <div class ="yellow">
<p class = "pindescription2">New York, NY </p>
      </div>

    </div>
    <div class= "box2">
      <div class ="yellow">
          <p class = "pindescription2"> Honolulu, HI </p>
      </div>

    </div>
    <div class= "box3">
      <div class ="yellow">

<p class = "pindescription2">Reno, NV </p>
      </div>

    </div>
  </div>
</div>

<div class ="lightblue">

  <p>Start Exploring</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Views</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://use.typekit.net/spu8mfr.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>
</head>
<body>

  <nav class="navbar navbar-inverse navbar-fixed-top color">
     <div class="container">
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
         <%= link_to "THE VIEWS", root_path, class: "navbar-brand colortwo" %>
       </div>

       <div id="navbar" class="collapse navbar-collapse">
             <ul class="nav navbar-nav">

             </ul>

         <ul class="nav navbar-nav navbar-right colortwo">
           <% if user_signed_in?%>
              <li><%= link_to 'Pins', pins_path %></li>
           <li><%= link_to 'Profile',edit_user_registration_path %></li>
          <li> <%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>


           <% else %>
           <li><%= link_to 'Login', new_user_session_path %></li>
           <li><%= link_to 'Sign Up', new_user_registration_path %></li>
           <% end%>
         </ul>
       </div>
     </div>
   </nav>



  <!--<p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>-->

<%= yield %>


<footer class ="footer">


</footer>
</body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>


  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.file_field :pin_image %>

<div class="field">
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div class ="picheader2">
  <h2> Adventure Awaits.</h2>
</div>

<div class ="wrap">
<div class="row">
  <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3">
    <div class="input-group">

      <input type="text" class="form-control" placeholder="Search...">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button">Go!</button>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->

<div class ="topspace2">
<div class ="container">
  <div class = "grid row">

  <% @pins.each do |pin| %>
    <div class = "grid-item col-md-4 col-sm-3 col-xs-12">

      <div class = "group">

        <%= link_to image_tag(pin.pin_image.url(:medium)), pin %>

          <div class ="newyellow">
             <h4 class ="pindescription2">  <%= pin.title %></h4>
            <h4>   <%= link_to image_tag(pin.user.avatar.url(:thumb), :class => "img-circle size6" ), user_path(pin.user.username)  %></h4>
           </div>


      </div>

    </div>
  <% end %>
  </div>
</div>
</div>

<div class ="row">
<div class = "col-xs-6 col-xs-offset-3 col-md-6 col-md-offset-3">

</div>
</div>
</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>



</p>

<div class = "picbackground">
<%= image_tag(@pin.pin_image.url, :class => "background") %>
</div>

<div class ="wrap5">
  <div class ="content">
      <div class = "pinprofile">
        <h4 class="pincolor">View found by</h4>
        <h3 class ="pincolor2">  <%= @pin.user.username %></h3>
        <p> <%= image_tag(@pin.user.avatar.url(:medium), :class => "img-circle size5" )%></p>

        <p class = "bio2"><%= @pin.user.bio %></p>
      </div>


      <div class = "viewinfo">

        <!--<%= @pin.title %>-->
        <h2 class="pincolor"><%= @pin.title %></h2>
        <h3>Coordinates 43.25.46</h3>
      <p>  <%= @pin.description %></p>

        <div class = "pinlinks">
          <ul>
          <li><%= image_tag("_heart.png", :class => "pinlink" )%></li>
          <li><%= image_tag("_plus.png", :class => "pinlink" )%></li>
          <li><%= image_tag("_Share.png", :class => "pinlink" )%></li>
        </ul>
        </div>

      </div>
  </div>
</div>

<!--
<div class ="links">

  <%= link_to 'Edit', edit_pin_path(@pin) %> |
    <%= link_to 'Destroy', @pin, method: :delete, data: { confirm: 'Are you sure?' } %>
  <%= link_to 'Back', pins_path %>

</div>

-->

app/views/users/show.html.erb
<div class ="picheader3">
  <div class ="profile">

    <p> <%= image_tag(@user.avatar.url(:medium), :class => "img-circle size2" )%></p>
    <div class ="bio">
  <h4 class ="username"> <%= @user.username %></h4>
  <p class ="userbio"> <%= @user.bio %></p>
</div>
</div>

</div>

  </div>
</div>

<div class ="wrap">
<div class ="pinbuttons">
    <%= link_to 'New Pin', new_pin_path, class: "btn btn-primary new", type:"button" %>
    <%= link_to 'Edit Profile', edit_user_registration_path , class: "btn btn-primary new", type:"button" %>
</div>
<div class ="topspace">
<% @user.pins.each do |pin| %>
<div class = "grid-item col-md-4 col-sm-3 col-xs-12 ">
  <div class = "group">


    <%= link_to image_tag(pin.pin_image.url(:medium)), pin %>

      <div class ="newyellow">
         <h4 class ="pindescription2">  <%= pin.title %></h4>
         <p class ="size3"><%= link_to '', edit_pin_path(pin), class: "glyphicon glyphicon-pencil" %></p>
        <p class ="size4"> <%= link_to '', pin, method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-trash" %></p>
       </div>


  </div>

</div>




<% end %>
</div>
</div>